// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Lang 绑定服务：文案来自 locales 目录下的 JSON。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * AvailableLocales 返回已嵌入的语言标识列表（排序后）。
 * @returns {$CancellablePromise<string[]>}
 */
export function AvailableLocales() {
    return $Call.ByID(1470219162).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Bundle 返回指定语言的完整键值表（用于前端一次性注入）；未知语言返回空 map。
 * @param {string} locale
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function Bundle(locale) {
    return $Call.ByID(2819942104, locale).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CurrentLocale 返回当前语言。
 * @returns {$CancellablePromise<string>}
 */
export function CurrentLocale() {
    return $Call.ByID(2191260695);
}

/**
 * SetLocale 切换语言并向前端派发 localeChanged 事件。
 * @param {string} locale
 * @returns {$CancellablePromise<void>}
 */
export function SetLocale(locale) {
    return $Call.ByID(858335402, locale);
}

/**
 * T 按当前语言翻译 key；缺失时返回 key。
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function T(key) {
    return $Call.ByID(2365024988, key);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
