// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Conn is a generic stream-oriented network connection.
 * 
 * Multiple goroutines may invoke methods on a Conn simultaneously.
 * @typedef {any} Conn
 */
