// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PACConfig {
    /**
     * Creates a new PACConfig instance.
     * @param {Partial<PACConfig>} [$$source = {}] - The source object to create the PACConfig.
     */
    constructor($$source = {}) {
        if (!("domains" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["domains"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PACConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PACConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PACConfig(/** @type {Partial<PACConfig>} */($$parsedSource));
    }
}

export class ProxySettings {
    /**
     * Creates a new ProxySettings instance.
     * @param {Partial<ProxySettings>} [$$source = {}] - The source object to create the ProxySettings.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("latencyTestHost" in $$source)) {
            /**
             * LatencyTestHost 延迟探测用的 HTTP 目标，形如 host、host:port（默认 80）。
             * @member
             * @type {string}
             */
            this["latencyTestHost"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxySettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxySettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxySettings(/** @type {Partial<ProxySettings>} */($$parsedSource));
    }
}

/**
 * ServerEntry 与前端服务器列表项一致（不含运行时延迟字段）。
 */
export class ServerEntry {
    /**
     * Creates a new ServerEntry instance.
     * @param {Partial<ServerEntry>} [$$source = {}] - The source object to create the ServerEntry.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("remark" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remark"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("protocol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerEntry(/** @type {Partial<ServerEntry>} */($$parsedSource));
    }
}

/**
 * Settings 与前端 settings store 持久化 JSON 一致。
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("proxy" in $$source)) {
            /**
             * @member
             * @type {ProxySettings}
             */
            this["proxy"] = (new ProxySettings());
        }
        if (!("system" in $$source)) {
            /**
             * @member
             * @type {SystemSettings}
             */
            this["system"] = (new SystemSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("proxy" in $$parsedSource) {
            $$parsedSource["proxy"] = $$createField0_0($$parsedSource["proxy"]);
        }
        if ("system" in $$parsedSource) {
            $$parsedSource["system"] = $$createField1_0($$parsedSource["system"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

export class SystemSettings {
    /**
     * Creates a new SystemSettings instance.
     * @param {Partial<SystemSettings>} [$$source = {}] - The source object to create the SystemSettings.
     */
    constructor($$source = {}) {
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("themeMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["themeMode"] = "";
        }
        if (!("startupOnBoot" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["startupOnBoot"] = false;
        }
        if (!("enableLogRecording" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableLogRecording"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemSettings(/** @type {Partial<SystemSettings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ProxySettings.createFrom;
const $$createType1 = SystemSettings.createFrom;
