// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(3518976984);
}

/**
 * GetServers 无记录时返回空切片。
 * @returns {$CancellablePromise<$models.ServerEntry[]>}
 */
export function GetServers() {
    return $Call.ByID(2458702056).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetSettings 无记录时返回 nil, nil。
 * @returns {$CancellablePromise<$models.Settings | null>}
 */
export function GetSettings() {
    return $Call.ByID(3566655053).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {$models.ServerEntry[]} servers
 * @returns {$CancellablePromise<void>}
 */
export function SetServers(servers) {
    return $Call.ByID(526400564, servers);
}

/**
 * @param {$models.Settings} v
 * @returns {$CancellablePromise<void>}
 */
export function SetSettings(v) {
    return $Call.ByID(474458257, v);
}

// Private type creation functions
const $$createType0 = $models.ServerEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Settings.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
