// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * o  ATYP   address type of following address
 * 
 * 	o  IP V4 address: X'01'
 * 	o  DOMAINNAME: X'03'
 * 	o  IP V6 address: X'04'
 * @readonly
 * @enum {number}
 */
export const ATYP = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    ATYP_IPV4: 1,
    ATYP_DOMAIN: 3,
    ATYP_IPV6: 4,
};

/**
 * o  CMD
 * 
 * 	o  CONNECT X'01'
 * 	o  BIND X'02'
 * 	o  UDP ASSOCIATE X'03'
 * @readonly
 * @enum {number}
 */
export const CMD = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    CMD_CONNECT: 1,
    CMD_BIND: 2,
    CMD_UDP_ASSOCIATE: 3,
};

export class Requests {
    /**
     * Creates a new Requests instance.
     * @param {Partial<Requests>} [$$source = {}] - The source object to create the Requests.
     */
    constructor($$source = {}) {
        if (!("CMD" in $$source)) {
            /**
             * @member
             * @type {CMD}
             */
            this["CMD"] = CMD.$zero;
        }
        if (!("ATYP" in $$source)) {
            /**
             * @member
             * @type {ATYP}
             */
            this["ATYP"] = ATYP.$zero;
        }
        if (!("DST_ADDR" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DST_ADDR"] = "";
        }
        if (!("DST_PORT" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DST_PORT"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Requests instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Requests}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("DST_ADDR" in $$parsedSource) {
            $$parsedSource["DST_ADDR"] = $$createField2_0($$parsedSource["DST_ADDR"]);
        }
        return new Requests(/** @type {Partial<Requests>} */($$parsedSource));
    }
}
