// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['Storage']['Close']();
}

export function Delete(arg1) {
  return window['go']['main']['Storage']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['main']['Storage']['Get'](arg1);
}

export function Set(arg1, arg2) {
  return window['go']['main']['Storage']['Set'](arg1, arg2);
}
