// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Close():Promise<void>;

export function Delete(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<any>;

export function Set(arg1:string,arg2:any):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
