// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * Conn is a generic stream-oriented network connection.
 * 
 * Multiple goroutines may invoke methods on a Conn simultaneously.
 * @typedef {$models.Conn} Conn
 */
