// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as net$0 from "../../net/models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(1212832896);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ListenAndServe() {
    return $Call.ByID(820946283);
}

/**
 * @param {net$0.Conn} conn
 * @returns {$CancellablePromise<void>}
 */
export function ProxyHTTP(conn) {
    return $Call.ByID(4136432300, conn);
}

/**
 * @param {net$0.Conn} conn
 * @returns {$CancellablePromise<void>}
 */
export function ProxySocks5(conn) {
    return $Call.ByID(3266134104, conn);
}

/**
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetMode(mode) {
    return $Call.ByID(4108844599, mode);
}

/**
 * @param {string} remote
 * @returns {$CancellablePromise<void>}
 */
export function SetRemote(remote) {
    return $Call.ByID(2086093330, remote);
}

/**
 * @param {string} host
 * @param {string} user
 * @param {string} pass
 * @returns {$CancellablePromise<void>}
 */
export function SetStart(host, user, pass) {
    return $Call.ByID(922223448, host, user, pass);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SetStop() {
    return $Call.ByID(1757767676);
}
