// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.appConst>}
 */
export function AppConfig() {
    return $Call.ByID(2962763604).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} rawURL
 * @returns {$CancellablePromise<void>}
 */
export function OpenExternalURL(rawURL) {
    return $Call.ByID(1935962305, rawURL);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ProxyScheme() {
    return $Call.ByID(140277774).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.appConst.createFrom;
const $$createType1 = $Create.Array($Create.Any);
