// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class appConst {
    /**
     * Creates a new appConst instance.
     * @param {Partial<appConst>} [$$source = {}] - The source object to create the appConst.
     */
    constructor($$source = {}) {
        if (!("LogTypeName_STATUS" in $$source)) {
            /**
             * 应用运行状态日志名称
             * @member
             * @type {string}
             */
            this["LogTypeName_STATUS"] = "";
        }
        if (!("LogTypeName_LOG" in $$source)) {
            /**
             * 连接日志列表的消息名称
             * @member
             * @type {string}
             */
            this["LogTypeName_LOG"] = "";
        }
        if (!("EventNameLocaleChanged" in $$source)) {
            /**
             * 语言切换事件（payload 为语言标识字符串）
             * @member
             * @type {string}
             */
            this["EventNameLocaleChanged"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new appConst instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {appConst}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new appConst(/** @type {Partial<appConst>} */($$parsedSource));
    }
}
