// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as Proxy from "./proxy.js";
import * as Storage from "./storage.js";
export {
    Proxy,
    Storage
};
