// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppConst {
    /**
     * Creates a new AppConst instance.
     * @param {Partial<AppConst>} [$$source = {}] - The source object to create the AppConst.
     */
    constructor($$source = {}) {
        if (!("LogTypeName_STATUS" in $$source)) {
            /**
             * 应用运行状态日志名称
             * @member
             * @type {string}
             */
            this["LogTypeName_STATUS"] = "";
        }
        if (!("LogTypeName_LOG" in $$source)) {
            /**
             * 连接日志列表的消息名称
             * @member
             * @type {string}
             */
            this["LogTypeName_LOG"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConst instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppConst}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppConst(/** @type {Partial<AppConst>} */($$parsedSource));
    }
}

export class PingRequest {
    /**
     * Creates a new PingRequest instance.
     * @param {Partial<PingRequest>} [$$source = {}] - The source object to create the PingRequest.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("protocol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PingRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PingRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PingRequest(/** @type {Partial<PingRequest>} */($$parsedSource));
    }
}

export class PingResult {
    /**
     * Creates a new PingResult instance.
     * @param {Partial<PingResult>} [$$source = {}] - The source object to create the PingResult.
     */
    constructor($$source = {}) {
        if (!("latency" in $$source)) {
            /**
             * 延迟（毫秒）
             * @member
             * @type {number}
             */
            this["latency"] = 0;
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PingResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PingResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PingResult(/** @type {Partial<PingResult>} */($$parsedSource));
    }
}
