// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} host
 * @param {string} user
 * @param {string} pass
 * @returns {$CancellablePromise<void>}
 */
export function SetRemote(host, user, pass) {
    return $Call.ByID(1742491558, host, user, pass);
}

/**
 * @param {string} host
 * @param {string} user
 * @param {string} pass
 * @returns {$CancellablePromise<void>}
 */
export function Start(host, user, pass) {
    return $Call.ByID(2984906812, host, user, pass);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(1134319448);
}
