// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetMode(mode) {
    return $Call.ByID(2511165443, mode);
}

/**
 * @param {string} remote
 * @returns {$CancellablePromise<void>}
 */
export function SetRemote(remote) {
    return $Call.ByID(1742491558, remote);
}

/**
 * @param {string} host
 * @param {string} user
 * @param {string} pass
 * @returns {$CancellablePromise<void>}
 */
export function SetStart(host, user, pass) {
    return $Call.ByID(373722444, host, user, pass);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SetStop() {
    return $Call.ByID(513036456);
}
