// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * TestServer 通过 HandleConnect 经代理访问 Google（HTTP）并测量首字节响应延迟。
 * @param {string} serverURL
 * @returns {$CancellablePromise<$models.ProxyPingResult>}
 */
export function TestServer(serverURL) {
    return $Call.ByID(2977024831, serverURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ProxyPingResult.createFrom;
