// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(2567311041);
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function Delete(key) {
    return $Call.ByID(1997819208, key);
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<any>}
 */
export function Get(key) {
    return $Call.ByID(2357268917, key);
}

/**
 * @param {string} key
 * @param {any} value
 * @returns {$CancellablePromise<void>}
 */
export function Set(key, value) {
    return $Call.ByID(177158985, key, value);
}
