// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetMode(mode) {
    return $Call.ByID(1601215220, mode);
}

/**
 * @param {string} remote
 * @returns {$CancellablePromise<void>}
 */
export function SetRemote(remote) {
    return $Call.ByID(2009944977, remote);
}

/**
 * @param {string} host
 * @param {string} user
 * @param {string} pass
 * @returns {$CancellablePromise<void>}
 */
export function SetStart(host, user, pass) {
    return $Call.ByID(457817641, host, user, pass);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SetStop() {
    return $Call.ByID(1614014531);
}
